name: "CI"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build shared package
        run: npm run build --workspace=@turn-based-mcp/shared

      - name: Verify shared build artifacts
        run: |
          test -f shared/dist/index.js || (echo 'shared/dist/index.js missing' && exit 1)
          test -f shared/dist/testing/index.js || (echo 'shared/dist/testing/index.js missing' && exit 1)

      - name: Type check all workspaces
        run: npm run type-check

      - name: Build web package
        run: npm run build --workspace=@turn-based-mcp/web

      - name: Build mcp-server package
        run: npm run build --workspace=@turn-based-mcp/mcp-server

      - name: Run tests - shared
        run: npm run test --workspace=@turn-based-mcp/shared

      - name: Run tests - web
        run: npm run test --workspace=@turn-based-mcp/web

      - name: Run tests - mcp-server
        run: npm run test --workspace=@turn-based-mcp/mcp-server

      - name: Lint all packages
        run: npm run lint:all